name: google_map
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  quickalert: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  logger: ^1.3.0

flutter:
  uses-material-design: true
