name: google_map
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  google_maps_routes: ^1.1.2
  point_in_polygon: ^1.0.0
  quickalert: ^1.0.1
  xml2json: ^5.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  logger: ^1.3.0

flutter:
  uses-material-design: true
